### ISSUE TITLE
Code of text extraction from PDF

### ISSUE THREAD

**Issue by WangXuan2401** [saturnMars/derivingStructuredInsightsFromSustainabilityReportsViaLargeLanguageModels#1]
Hi, Thanks for your great and detailed work!

We recently try to apply your proposed model in new kind of sustainability reports, but we cannot get a very standard and clear textual file by using PDF parser (PyMuPDF).

Could u provide us with more details and codes of the text extraction process.

Thank u for your time!

**Comment by saturnMars** [comment]
Added the code for text extraction of PDFs (e3d58b195bf82fe5e32266d61f6b0875312fd09a)

**Comment by WangXuan2401** [comment]
> Added the code for text extraction of PDFs ([e3d58b1](https://github.com/saturnMars/derivingStructuredInsightsFromSustainabilityReportsViaLargeLanguageModels/commit/e3d58b195bf82fe5e32266d61f6b0875312fd09a))

Thank you so much for your help!
