### ISSUE TITLE
esg_topics

### ISSUE THREAD

**Issue by nishuone028** [saturnMars/derivingStructuredInsightsFromSustainabilityReportsViaLargeLanguageModels#3]
I would like to know what is the format of the esg_topics.json file?

can u help me?

thanks

**Comment by saturnMars** [comment]
What do you mean by format? 
It's a list of ESG-related categories extrapolated from Table IV (4) of [Berg et al. 's work](https://academic.oup.com/rof/article/26/6/1315/6590670) and was used in the pipeline for (i) _filtering the sentences_ and (ii) _enhancing the model's prompt_.

Please refer to the [paper](https://epjdatascience.springeropen.com/articles/10.1140/epjds/s13688-024-00481-2), for more details concerning:

- The data source:  _Section 3.1.2_ and _Data Availability section_
- Usage for sentence filtering:  _Section 3.2.2_
- Usage within the prompt: _Section 3.3_ and _Section 2.1_ of the [Supplementary Material document](https://static-content.springer.com/esm/art%3A10.1140%2Fepjds%2Fs13688-024-00481-2/MediaObjects/13688_2024_481_MOESM1_ESM.pdf)

**Comment by nishuone028** [comment]
> What do you mean by format? It's a list of ESG-related categories extrapolated from Table IV (4) of [Berg et al. 's work](https://academic.oup.com/rof/article/26/6/1315/6590670) and was used in the pipeline for (i) _filtering the sentences_ and (ii) _enhancing the model's prompt_.
> 
> Please refer to the [paper](https://epjdatascience.springeropen.com/articles/10.1140/epjds/s13688-024-00481-2), for more details concerning:
> 
> * The data source:  _Section 3.1.2_ and _Data Availability section_
> * Usage for sentence filtering:  _Section 3.2.2_
> * Usage within the prompt: _Section 3.3_ and _Section 2.1_ of the [Supplementary Material document](https://static-content.springer.com/esm/art%3A10.1140%2Fepjds%2Fs13688-024-00481-2/MediaObjects/13688_2024_481_MOESM1_ESM.pdf)

Thank you very much for your reply. Yesterday I was reading your paper and found out how to solve this problem.
